openapi: 3.0.2
info:
  contact:
    email: DL-T-Magic.Hugo@telekom.de
    name: Team Hugo
  description: A microservice to manage presales order confirmations
  title: Order Confirmation Service
  version: 0.9.0
servers:
  - url: /
paths:
  /v1/greeting:
    post:
      description: provide a greeting
      operationId: v1greeting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreetingRequest'
        description: parameters for an order confirmation
        required: false
      responses:
        "200":
          #description: success
          $ref: '#/components/responses/Success'
        "400":
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - greeting
components:
  responses:
    GreetingResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Greeting'
      description: ""
    ProblemDetails:
      description: |
        Problem Details based upon the RFC 7807 format.
        See https://gard.telekom.de/gardwiki/display/DGHB/Problem+Message
        and https://tools.ietf.org/html/rfc7807#page-5 for more details.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    Success:
      description: |
        Problem Details based upon the RFC 7807 format.
        See https://gard.telekom.de/gardwiki/display/DGHB/Problem+Message
        and https://tools.ietf.org/html/rfc7807#page-5 for more details.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/SuccessMessage'
  schemas:
    ErrorMessage:
      type: object
      title: Error Message
      description: |
        Problem Details based upon the RFC 7807 format.
        See https://gard.telekom.de/gardwiki/display/DGHB/Problem+Message
        and https://tools.ietf.org/html/rfc7807#page-5 for more details.
      properties:
        error:
          type: string
          example: ""
      required:
        - error
    SuccessMessage:
      type: object
      title: Success Message
      description: |
        success case
      properties:
        greeting:
          type: string
          example: "Hello Jenny Musterfrau"
      required:
        - greeting
    Greeting:
      properties:
        salutation:
          description: Anrede
          example: Herr
          type: string
        firstName:
          description: FirstName of the customer only needed for private customers
          type: string
        lastName:
          description: LastName of the customer only needed for private customers
          type: string
      type: object
    GreetingRequest:
      properties:
        salutation:
          description: deutsche Anrede für eine Begrüßnug
          type: string
          example: Frau
          enum:
            - Frau
            - Herr
        firstName:
          description: FirstName of the customer only needed for private customers
          type: string
          example: Jenny
        lastName:
          description: LastName of the customer only needed for private customers
          type: string
          example: Mustermann
      required:
        - lastName
      type: object
