openapi: 3.0.2
info:
  contact:
    email: DL-T-Magic.Hugo@telekom.de
    name: Team Hugo
  description: A microservice to manage presales order confirmations
  title: Order Confirmation Service
  version: 0.9.0
servers:
  - url: /
paths:
  /v1/greeting:
    post:
      description: provide a greeting
      operationId: v1greeting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GreetingRequest'
        description: parameters for an order confirmation
        required: false
      responses:
        "200":
          #description: success
          $ref: '#/components/responses/GreetingResponse'
        "400":
          $ref: '#/components/responses/ProblemDetails'
      tags:
        - greeting
components:
  responses:
    ProblemDetails:
      description: |
        Problem Details
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
    GreetingResponse:
      description: |
        Success Details
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessMessage'
  schemas:
    ErrorMessage:
      type: object
      title: Error Message
      description: |
        Problem Details
      properties:
        error:
          type: string
          example: ""
      required:
        - error
    SuccessMessage:
      type: object
      title: Success Message
      description: |
        success message
      properties:
        message:
          type: string
          example: "Hello Jenny Musterfrau"
      required:
        - message
    GreetingRequest:
      properties:
        salutation:
          description: deutsche Anrede für eine Begrüßnug
          type: string
          example: Frau
          enum:
            - Frau
            - Herr
            - Divers
        firstName:
          description: FirstName of the customer only needed for private customers
          type: string
          example: Jenny
        lastName:
          description: LastName of the customer only needed for private customers
          type: string
          example: Mustermann
      required:
        - lastName
      type: object
