// Package dtos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package dtos

// Defines values for GreetingRequestSalutation.
const (
	Frau GreetingRequestSalutation = "Frau"
	Herr GreetingRequestSalutation = "Herr"
)

// GreetingRequest defines model for GreetingRequest.
type GreetingRequest struct {
	// FirstName of the customer only needed for private customers
	FirstName *string `json:"firstName,omitempty"`

	// LastName of the customer only needed for private customers
	LastName string `json:"lastName"`

	// deutsche Anrede für eine Begrüßnug
	Salutation *GreetingRequestSalutation `json:"salutation,omitempty"`
}

// deutsche Anrede für eine Begrüßnug
type GreetingRequestSalutation string

// Problem Details based upon the RFC 7807 format.
// See https://gard.telekom.de/gardwiki/display/DGHB/Problem+Message
// and https://tools.ietf.org/html/rfc7807#page-5 for more details.
type ProblemDetails struct {
	// Non-RFC7807 property but mandatory for Gigabit, contains for a specific case the defined error-codes. see definition in response section with x-error-codes
	Code int `json:"code"`

	// A human-readable explanation specific to this occurrence of the problem.
	// The "detail" member, if present, ought to focus on helping
	// the client correct the problem, rather than giving debugging information.
	Detail *string `json:"detail,omitempty"`

	// HTTP status code ([RFC7231], Section 6).
	Status *int `json:"status,omitempty"`

	// A short, human-readable summary of the problem type. Consumers
	// SHOULD NOT automatically dereference the type URI.
	Title string `json:"title"`

	// A URI reference [RFC3986] that identifies the problem type.
	Type string `json:"type"`
}

// success case
type Success struct {
	// Non-RFC7807 property but mandatory for Gigabit, contains for a specific case the defined error-codes. see definition in response section with x-error-codes
	Code int `json:"code"`

	// A human-readable explanation specific to this occurrence of the problem.
	// The "detail" member, if present, ought to focus on helping
	// the client correct the problem, rather than giving debugging information.
	Detail *string `json:"detail,omitempty"`

	// HTTP status code ([RFC7231], Section 6).
	Status *int `json:"status,omitempty"`

	// A short, human-readable summary of the problem type. Consumers
	// SHOULD NOT automatically dereference the type URI.
	Title string `json:"title"`

	// A URI reference [RFC3986] that identifies the problem type.
	Type string `json:"type"`
}

// V1greetingJSONBody defines parameters for V1greeting.
type V1greetingJSONBody = GreetingRequest

// V1greetingJSONRequestBody defines body for V1greeting for application/json ContentType.
type V1greetingJSONRequestBody = V1greetingJSONBody
