// Package dtos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package dtos

// Defines values for GreetingRequestSalutation.
const (
	Frau GreetingRequestSalutation = "Frau"
	Herr GreetingRequestSalutation = "Herr"
)

// Problem Details based upon the RFC 7807 format.
// See https://gard.telekom.de/gardwiki/display/DGHB/Problem+Message
// and https://tools.ietf.org/html/rfc7807#page-5 for more details.
type ErrorMessage struct {
	Error string `json:"error"`
}

// GreetingRequest defines model for GreetingRequest.
type GreetingRequest struct {
	// FirstName of the customer only needed for private customers
	FirstName *string `json:"firstName,omitempty"`

	// LastName of the customer only needed for private customers
	LastName string `json:"lastName"`

	// deutsche Anrede für eine Begrüßnug
	Salutation *GreetingRequestSalutation `json:"salutation,omitempty"`
}

// deutsche Anrede für eine Begrüßnug
type GreetingRequestSalutation string

// success case
type SuccessMessage struct {
	Success string `json:"success"`
}

// V1greetingJSONBody defines parameters for V1greeting.
type V1greetingJSONBody = GreetingRequest

// V1greetingJSONRequestBody defines body for V1greeting for application/json ContentType.
type V1greetingJSONRequestBody = V1greetingJSONBody
